### ISSUE TITLE
Code Update

### ISSUE THREAD

**Issue by sarvet** [DigitalHERMES/ardopc#2]
Hi, I want to update the modems code, but as there are multiple folders called ARDOP or ardop in the "TeensyProjects.zip" file and G8BPQ also uses a beta/ hierarchy on his page's downloads but not really any VCS for his code (except the g8bpq profile with LinBPQ and BPQ32) it's not really clear which code is worked on and in now...

**Comment by rafael2k** [comment]
Hi. ardop1ofdm is ardop1ofdm directory, and ardop2ofdm is ardopofdm directory.
